ci:
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.19.1'
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
  - repo: https://github.com/PyCQA/isort
    rev: '5.8.0'
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: '21.5b2'
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.10.0
    hooks:
      - id: nbqa-black
      - id: nbqa-pyupgrade
